import Head from "next/head";
import About from "../components/About";
import Introduction from "../components/Introduction";
import Navbar from "../components/Navbar";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Santanu Ghosh &#128516; </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <div>
        <Navbar />
        <div>
          <div id="introduction">
            <Introduction />
          </div>
          <div id="about">
            <About />
          </div>
          <div id="skills">
            <Skills />
          </div>
        </div>
      </div>
    </>
  );
}
